trailingComma: none
bracketSpacing: true
semi: true
singleQuote: true
arrowParens: avoid
endOfLine: lf
htmlWhitespaceSensitivity: css
jsxBracketSameLine: false
printWidth: 80
proseWrap: preserve
requirePragma: false
tabWidth: 2
useTabs: false
