version: 2.1

_common:
  node-docker: &node-docker
    - image: circleci/node:10.13.0
  restore-cache: &restore-cache
    keys:
      - bootstrap-v1-{{ .Branch }}-{{ .Revision }}
  attach-workspace: &attach-workspace
    at: .

jobs:
  bootstrap:
    docker: *node-docker
    steps:
      - restore_cache: *restore-cache
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - add_ssh_keys:
          fingerprints:
            - $FINGERPRINT
      - run:
          name: Install deps
          command: npm install

      - run:
          name: Generate build
          command: npm run build
          
      - save_cache:
          key: bootstrap-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  test:
    docker: *node-docker
    steps:
      - restore_cache: *restore-cache
      - run:
          name: Run tests
          command: npm run test:once

  release:
    docker: *node-docker
    steps:
      - restore_cache: *restore-cache
      - run:
          name: Generate release
          command: npm run release

      - run:
          name: Publish
          command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ./npmrc && npm publish --tag latest


workflows:
  version: 2
  build-and-test:
    jobs:
      - bootstrap

      - test:
          requires:
            - bootstrap

      - release:
          requires:
            - bootstrap
            - test
          filters:
            branches:
              only: master