version: 2.1

_common:
  node-docker: &node-docker
    - image: circleci/node:10.13.0
  restore-cache: &restore-cache
    keys:
      - bootstrap-v1-{{ .Branch }}-{{ .Revision }}
  attach-workspace: &attach-workspace
    at: .

jobs:
  bootstrap:
    docker: *node-docker
    steps:
      - restore_cache: *restore-cache
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $FINGERPRINT
      - run:
          name: install deps
          command: npm install

      - save_cache:
          key: bootstrap-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  build:
    docker: *node-docker
    steps:
      - restore_cache: *restore-cache
      - run:
          name: Run build
          command: npm run build


  test:
    docker: *node-docker
    steps:
      - restore_cache: *restore-cache
      - run:
          name: Run tests
          command: npm run test:once

workflows:
  version: 2
  build-and-test:
    jobs:
      - bootstrap

      - build:
          requires:
            - bootstrap

      - test:
          requires:
            - bootstrap
            - build