version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $FINGERPRINT
      - run:
          command: npm install
      - run:
          command: npm run test:once